version: '2'

services:
  confluence:
    image: blacklabelops/confluence
    container_name: confluence
    hostname: confluence
    networks:
      - confluencenet
    volumes:
      - confluencedata:/var/atlassian/confluence
    ports:
      - '80:8090'
      - '8091:8091'
    environment:
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
      - 'CONFLUENCE_PROXY_NAME=devpyo.iptime.org'
      - 'CONFLUENCE_PROXY_PORT=443'
      - 'CONFLUENCE_PROXY_SCHEME=https'
      - 'CONFLUENCE_DELAYED_START=10s'
    labels:
      com.blacklabelops.description: "Atlassian Confluence"
      com.blacklabelops.service: "confluence"

  postgresql:
    image: blacklabelops/postgres
    container_name: postgres
    hostname: postgres
    networks:
      - confluencenet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=confluencedb'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=jellyfish'
      - 'POSTGRES_DB=confluencedb'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    labels:
      com.blacklabelops.description: "PostgreSQL Database Server"
      com.blacklabelops.service: "postgresql"

  nginx:
    image: blacklabelops/nginx
    container_name: nginx
    hostname: nginx
    networks:
      - confluencenet
    environment:
      - 'SERVER1REVERSE_PROXY_LOCATION1=/'
      - 'SERVER1REVERSE_PROXY_PASS1=http://confluence:8090'
      - 'SERVER1REVERSE_PROXY_APPLICATION1=confluence'
      - 'SERVER1CERTIFICATE_DNAME=/CN=CrustyClown/OU=SpringfieldEntertainment/O=devpyo.iptime.org/L=Springfield/C=US'
      - 'SERVER1HTTPS_ENABLED=true'
      - 'SERVER1HTTP_ENABLED=false'
    ports:
      - '443:443'

volumes:
  confluencedata:
    external: false
  postgresqldata:
    external: false

networks:
  confluencenet:
    driver: bridge
